# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "2025 ML Summer School"
subtitle: "website"
email: uwsunlab@uw.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: uwsunlab
github_username: uwsunlab
minimal_mistakes_skin: default
search: true
locale                   : "en-US"
title_separator          : "-"
url                      : https://uwsunlab.github.io 
baseurl                  : "/2025-MLSummerSchool" # the subpath of your site, e.g. "/blog"
repository               : "2025-MLSummerSchool" # GitHub repository to help with editing content
logo                     : "/assets/images/uwsunlab_logo.png"


# Build settings
markdown: kramdown
kramdown:
  input: GFM
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink:  /:categories/:title/
# paginate: 10  #  amount of posts to show
paginate_path: /_pages/page:num
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name   : "Univ. Wash"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # - scope:
  #     path: "_pages"
  #     type: pages
  #   values:
  #     layout: single  # Ensure this matches your home page layout
  #     author_profile: false
  # - scope:
  #     path: "_pages/home.md"
  #     type: pages
  #   values:
  #     permalink: "/"
  #     layout: splash  # Or any layout you prefer

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development



